#!/usr/bin/env python
# encoding: utf-8

import os
import fnmatch


def build(bld):
    # Includes
    includes_path = ".."

    # Get source files
    sources = []
    for root, _, filenames in os.walk(bld.path.abspath()):
        for filename in fnmatch.filter(filenames, "*.cpp"):
            sources.append(os.path.join(root, filename))

    sources = [f[len(bld.path.abspath()) + 1:] for f in sources]

    # Define additional required libraries for the tests
    test_required = {"check_grad.cpp": "UTILSCPP",
                     "check_kernel.cpp": "UTILSCPP"}

    # Compile all the tests
    for test in sources:
        if test in test_required and test_required[test] in bld.env["libs"]:
            bld.program(
                features="cxx",
                install_path=None,
                source=test,
                includes=includes_path,
                uselib=bld.env["libs"],
                use=bld.env["libname"],
                cxxflags=bld.get_env()["CXXFLAGS"],
                target=test[: len(test) - len(".cpp")],
            )
