#!/usr/bin/env python
# encoding: utf-8

from waflib import Logs


def build(bld):
    cxxflags = bld.get_env()["CXXFLAGS"]

    libs = bld.env["kernel_lib_libs"]
    libname = bld.env["kernel_lib_libname"]

    bld.program(
        features="cxx",
        install_path=None,
        source="test_kernel.cpp",
        includes=". ../../src",
        uselib=libs,
        use=libname,
        cxxflags=cxxflags,
        target="test_kernel",
    )

